//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwardsServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwardsServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EmptyDatabase {
            get {
                object obj = ResourceManager.GetObject("EmptyDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string reflecting the WebAllDataPage.txt
        /// </summary>
        internal static string WebAllDataPage {
            get {
                return ResourceManager.GetString("WebAllDataPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- This is in the HTML body already --&gt;
        ///&lt;form action=&quot;/&quot; style=&quot;width: 100%;&quot;&gt;
        ///  Account Name:&lt;br&gt;
        ///  &lt;input type=&quot;text&quot; name=&quot;accn&quot; value=&quot;Enter your login account name&quot;&gt;
        ///  &lt;br&gt;
        ///  Last name:&lt;br&gt;
        ///  &lt;input type=&quot;text&quot; name=&quot;lName&quot; value=&quot;Enter your last name (case matters)&quot;&gt;
        ///  &lt;br&gt;
        ///  Tutor:&lt;br&gt;
        ///  &lt;input type=&quot;text&quot; name=&quot;tutor&quot; value=&quot;Enter the tutor you are in&quot;&gt;
        ///  &lt;br&gt;&lt;br&gt;
        ///  &lt;input type=&quot;submit&quot; value=&quot;Submit&quot;&gt;
        ///&lt;/form&gt; .
        /// </summary>
        internal static string WebAuthentificationPage {
            get {
                return ResourceManager.GetString("WebAuthentificationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // currently does nothing.
        /// </summary>
        internal static string WebScripts {
            get {
                return ResourceManager.GetString("WebScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .error {
        ///    color: red;
        ///}
        ///
        ///input {
        ///    width: 100%;
        ///    height: 30px;
        ///}
        ///
        ///table {
        ///    width: 100%;
        ///    height: 100%;
        ///}
        ///td {
        ///    border: 1px solid black;
        ///}
        ///tr {
        ///    border: 1px solid black;
        ///}
        ///th {
        ///    font-style: oblique;
        ///    color: blue;
        ///}
        ///.tblEven {
        ///    background-color: lightgray;
        ///}.
        /// </summary>
        internal static string WebStyles {
            get {
                return ResourceManager.GetString("WebStyles", resourceCulture);
            }
        }
    }
}
